#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

cookbook 'apt', '~> 2.8.2'
cookbook 'apache2', '>= 1.0.0'
cookbook 'php', '~> 1.7.2'
cookbook 'xdebug', '~> 1.0.0'
cookbook 'composer', '~> 2.2.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
